[MBLINTER-3] [Android] Registration Screen UI and functionality
mrsicsasa/Hangoutz pull request #12
Opened 2024-11-20 15:34 UTC by bataneske

2024-11-21 10:28 UTC, Mentors2024 requested changes

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/ErrorMessage.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +    HangoutzTheme {
This Theme doesn't need to be used here. It's already in use in mainActivity.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +private fun Show() {
If you are not using this function, delete it.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterScreen.kt
> +
Delete empty line.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +    val confirm: String = "",
Rename to something more descriptive. confirm what?

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                incompleteError = "All fields must be filled!"
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                _uiState.value = _uiState.value.copy(nameError = "Name must be 3-25 characters")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                _uiState.value = _uiState.value.copy(emailError = "Email must be in correct format")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                    _uiState.value.copy(passwordError = "Password must contain at least one number and be minimum 8 characters long")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                _uiState.value = _uiState.value.copy(confirmError = "Password must match")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                } else if (response.code() == 409) {
Move status code to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                    _uiState.value = _uiState.value.copy(emailError = "Email already in use")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +    val incompleteError: String = "",
Rename to something more descriptive.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +                _uiState.value = _uiState.value.copy(incompleteError = "An error has occurred")
Move error message to Constants.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/RegisterViewModel.kt
> +    fun userAuth(): Boolean {
This method can be private.
Rename this function. userAuth is more used for login not register.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/Validator.kt
Move this class do a different folder Utils for example.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/Validator.kt
> +    fun isUniqueEmail(): Boolean {
What does this function do. It's always returns true

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/Validator.kt
> +        confirm: String
Rename to something more descriptive.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/registerscreen/Validator.kt
> +    fun registerValidator(name: String, email: String, password: String, confirm: String): Boolean {
I haven't seen this function used anywhere. If its not used delete it, if it is rename it.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/theme/Type.kt
> -    bodyLarge = TextStyle(
Don't delete bodyLarge just add bodyMedium.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/theme/Type.kt
> -    titleLarge = TextStyle(
Don't delete titleLarge just add bodyLarge.

2024-11-21 10:28 UTC, Mentors2024 commented on app/src/main/res/values/strings.xml
> +    <string name="background_image">Background Image</string>
For what is this background_image used?

2024-11-21 11:46 UTC, bataneske commented
I've added .idea/Project_Default.xml to .idea/.gitignore because it's editing the IDE by re-enabling Settings -> Editor -> Inspections -> Proofreading against my preferences.
This way everyone can have their prefs how they like.

2024-11-22 10:04 UTC, Mentors2024 requested changes

2024-11-22 10:04 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/utils/Constants.kt
> +    val CONFLICT = 409
Describe error. What conflict?

2024-11-22 10:04 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/theme/Color.kt
> +val bottomNavigationColor = Color(red = 43, green = 42, blue = 58)
Set color to hex to match the others.

2024-11-22 10:04 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/utils/Validator.kt
> +            val regex = Regex(".*\\d.*")
Move regex to Constants.

2024-11-22 10:04 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/utils/Validator.kt
> +        return (email.endsWith("@gmail.com") == true)
Move string to Constants.

2024-11-22 10:04 UTC, Mentors2024 commented on .idea/.gitignore
> +/inspectionProfiles
Why did you add this to gitignore?

2024-11-22 10:09 UTC, bataneske commented on app/src/main/java/com/example/hangoutz/utils/Constants.kt
> +    val CONFLICT = 409
Error 409 is Conflict response. That's why I named it CONFLICT.  I could rename it to something more descriptive, but it wouldn't make sense if something like a duplicate event ends up using this error code.
In which case the best I can come up with is renaming it to DUPLICATE.

2024-11-22 10:10 UTC, bataneske commented on .idea/.gitignore
> +/inspectionProfiles
> I've added .idea/Project_Default.xml to .idea/.gitignore because it's editing the IDE by re-enabling Settings -> Editor -> Inspections -> Proofreading against my preferences. This way everyone can have their prefs how they like.

https://github.com/mrsicsasa/Hangoutz/pull/12#issuecomment-2490903625

2024-11-22 12:40 UTC, Mentors2024 requested changes

2024-11-22 12:40 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/utils/Constants.kt
> +    val CONFLICT = 409
Rename it to duplicate item in db or something like that.

2024-11-22 13:01 UTC, Mentors2024 approved these changes

2024-11-22 13:11 UTC, merged