MBLINTER-12 -profile screen UI and logout
mrsicsasa/Hangoutz pull request #14
Opened 2024-11-22 11:15 UTC by marija-drobac

2024-11-22 14:05 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +                { onNameChanged(it) },
ddf

2024-11-25 08:19 UTC, Mentors2024 requested changes

2024-11-25 08:19 UTC, Mentors2024 commented on app/build.gradle
> +    implementation  libs.compose
Delete double space.

2024-11-25 08:19 UTC, Mentors2024 commented on app/build.gradle
>      implementation(libs.androidx.hilt.navigation.compose)
Delete brackets.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/di/Module.kt
Format file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/domain/repository/UserRepository.kt
Format file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
Format file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
> +            fontSize = 32.sp,
Move font size to Type file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
> +
Delete empty lines.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
> +        //val keyboart = remember { Keyboard }
Delete unused line.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
Format file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
Format file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +                contentDescription = "",
Is contentDescription optional if it is delete this line.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +                fontSize = 20.sp,
Move to Type file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +@Composable
Move to separate file.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +fun NameInput(
Its convention to pass variables first and then functions.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +        val (x, y) = createRefs()
Rename x and y.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
> +
Remove empty line.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +        //Log.e("LOGG------ ","STATE = ${state} & ISREADONLY ${_uiState.value.isReadOnly}")
Remove commented line.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +
Remove empty line.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +                        userID!!,
Remove !!. If its not absolutely necessary don't use !!.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreen.kt
Move all dp to Dimensions file. Read Srdjan message on skype. Do this anywhere in code where you have dimensions.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +     val state =  !_uiState.value.isReadOnly
Rename this val state.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +                            avatar = if (it.avatar == null) "avatar_default.png" else it.avatar
Move default logo to constants.

2024-11-25 08:19 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
Format file and remove empty lines.

2024-11-25 11:02 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/SettingsScreenViewModel.kt
> +                        userID!!,
It's necessary,  code doesn't work without it,

2024-11-25 14:11 UTC, Mentors2024 requested changes

2024-11-25 14:11 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/NameInput.kt
> +                    .testTag("nameField")
Move to Constants.

2024-11-25 14:11 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settingsscreen/NameInput.kt
> +                    .testTag("nameField")
Do this for all test tags.

2024-11-25 14:11 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
> +
Remove emtpy line.

2024-11-25 14:18 UTC, Mentors2024 requested changes

2024-11-25 14:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/login/LoginScreen.kt
>                  text = getString(context, R.string.create_account_text),
stringResources(R.string.creat.e...)

2024-11-25 14:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +        getUser(context)
No need to pass context, it is injected in viewModel.

2024-11-25 14:53 UTC, Mentors2024 approved these changes

2024-11-25 14:53 UTC, merged