MBLINTER-13-profile screen-edit-functionality
mrsicsasa/Hangoutz pull request #31
Opened 2024-11-29 10:08 UTC by marija-drobac

2024-11-29 12:31 UTC, Mentors2024 requested changes

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/data/remote/UserAPI.kt
> +    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzanh3Zmp1dHN0cnlidmx0am92Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMDgwODE0MSwiZXhwIjoyMD
Move this Authorization key into the same file as first api key.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/data/remote/UserAPI.kt
> +    @DELETE("https://zsjxwfjutstrybvltjov.supabase.co/storage/v1/object/avatar/{avatarName}")
Move to build grade.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/data/remote/UserAPI.kt
> +    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzanh3Zmp1dHN0cnlidmx0am92Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMDgwODE0MSwiZXhwIjoyMD
Move this Authorization key into the same file as first api key.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/data/remote/UserAPI.kt
> +    @POST("https://zsjxwfjutstrybvltjov.supabase.co/storage/v1/object/avatar/{avatarName}")
Move to build grade.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/data/repository/UserRepositoryImpl.kt
> +    override suspend fun patchUserAvatarById(id: String, newAvatar: String): Response<Unit> {
Do we need this function since we are deleting avatar when we change it.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/GenerateFile.kt
> +            "com.example.hangoutz.fileprovider",
Move to Constants.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/GenerateFile.kt
> +        "MyAppImages"
Move to Constants.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/GenerateFile.kt
Maybe move this file to Utils?

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
> +    var showBottomSheet by remember { mutableStateOf(false) }
Move this to data class in view model. Then make a function that will change the state and call it on places where you are changing value.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
> +    var tempUri by remember { mutableStateOf<Uri?>(null) }
Same here move it to data class.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
Format file and remove empty lines.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +        if (_uiState.value.name.text.length >= 3 && _uiState.value.name.text.length <= 25) {
Use 3 and 25 from Constants.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
Format file and remove empty lines.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +                        val response3 =
Not response3 please. Rename it to something else for example responseForDeletingUser or something like that.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +                    val avatarNameGenerator = getRandomString(20) + ".jpg"
Move 20 and .jpg to Constants.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +                    if (_uiState.value.avatar != "avatar_default.png") {
We have this value either in Constants or in xml.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +                            val response2 = userRepository.patchUserAvatarById(
Rename it also.

2024-11-29 12:31 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/theme/Type.kt
> -        lineHeight = 24.sp,
Did you check if this will change UI in a places where we use this font?

2024-11-29 14:46 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/data/repository/UserRepositoryImpl.kt
> +    override suspend fun patchUserAvatarById(id: String, newAvatar: String): Response<Unit> {
yes we need it to edit the avatar name in users table

2024-11-29 15:42 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
> +    var tempUri by remember { mutableStateOf<Uri?>(null) }
causes issues in app

2024-11-29 15:44 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/ui/theme/Type.kt
> -        lineHeight = 24.sp,
yes, only I use it in Login screen and in Settings scrreen.

2024-12-02 10:11 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameField.kt
Delete unused imports

2024-12-02 10:12 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/NameInput.kt
Delete unused imports

2024-12-02 10:16 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
> +    val cameraPermissionLauncher = rememberLauncherForActivityResult(
Logic for managing temporary URIs and requesting camera permissions is currently in the composable. Move it to ViewModel

2024-12-02 10:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreen.kt
> +    if (data.value.showBottomSheet) {
Currently, composable manages the logic for launching the image picker and handling bottom sheet visibility. Extract this logic into a helper function in the ViewModel for managing the image handling flow.

2024-12-02 10:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +    fun setUri(uri: Uri) {
Can we remove this function since it's not in use?

2024-12-02 10:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +    fun saveName() {
This function can be private

2024-12-02 10:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +    fun iconSwitch() {
This function can be private

2024-12-02 10:22 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +    fun handleImage(imageUri: Uri) {
This function can be private

2024-12-02 10:23 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/settings/SettingsScreenViewModel.kt
> +                    if (postAvatarResponse != null) {
This condition can be removed since userRepository.postAvatar() is not nullable function thus postAvatarResponse will never be null

2024-12-04 08:52 UTC, Mentors2024 approved these changes

2024-12-04 08:53 UTC, Mentors2024 approved these changes

2024-12-04 09:00 UTC, merged