Feature/mblinter 96 event owner functionallity
mrsicsasa/Hangoutz pull request #48
Opened 2024-12-05 14:54 UTC by marija-drobac

event owner functionality

2024-12-06 08:18 UTC, Mentors2024 requested changes

2024-12-06 08:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/InputFieldWithIcon.kt
Format file.

2024-12-06 08:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/InputField.kt
Format file.

2024-12-06 08:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/events/EventScreenViewModel.kt
> +
Remove empty lines.

2024-12-06 08:18 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/events/EventsScreen.kt
> +fun isCurrentUserOwner(context: Context, event: EventCardDPO): Boolean {
Move to view model or see on which page you are and then based on that navigate to different screens.

2024-12-09 08:21 UTC, Mentors2024 requested changes

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/components/TimePicker.kt
> +        modifier = Modifier.clip(RoundedCornerShape(20.dp))
Use dp from dimensions file.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/createEvent/CreateEventScreen.kt
> -            if (sheetState.isVisible) {
Talk to Sasa this changes should stay.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +    private fun formatForDatabase() {
Move date formatting to Extensions file.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +    var isTitleError: Boolean = false,
Do we need all this errors even for the fields that can be empty?

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
>          val timeFormat = SimpleDateFormat("HH.mm", Locale.getDefault())
Time format should be HH:mm not HH.mm.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
>      private fun formatDateTime(dateTimeString: String): Pair<String, String> {
Move this function to Extensions.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +    fun checkIfInPast(date: String): Boolean {
Rename to isEventPassed.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        val inputFormat = SimpleDateFormat("dd.MM.yyyy. HH.mm", Locale.getDefault())
Remove . at the end of year.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        if (!validateTitle && !checkLength(_uiState.value.title, 25)) {
Move to Constants or use from constants if already exists.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        if (!validatePlace && !checkLength(_uiState.value.place, 25)) {
Same here.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        if (_uiState.value.description.length > 100) {
And here.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        if (_uiState.value.city.length > 25) {
And here.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        if (_uiState.value.street.length > 25) {
And also here.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +            "id=  ${_uiState.value.eventId.toString()}, newTitle =  ${_uiState.value.title}, newPlace = ${_uiState.value.place}, newDate =  ${_uiState.value.formattedDateForDatabase}"
Add space after id.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +        val formattedDateTime = outputFormat.format(inputFormat.parse(combined)!!)
Remove !!.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +                val eventResponse = eventRepository.patchEventById(
We should pass all fields not just required fields. This way if you update for example description event wont be updated.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
When we open calendar and time popup should have values from the event not default ones.

2024-12-09 08:21 UTC, Mentors2024 commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
We should be able to delete event even if we have participants. When we delete event first we need to delete all participants and then we can delete event.

2024-12-09 09:16 UTC, marija-drobac commented on app/src/main/java/com/example/hangoutz/ui/screens/eventDetailsOwner/EventDetailsOwnerViewModel.kt
> +    var isTitleError: Boolean = false,
yes, because the length cant me more than 25

2024-12-10 16:23 UTC, Mentors2024 approved these changes

2024-12-11 08:52 UTC, merged